### PR TITLE
Alternative php-fpm image

### PR DESCRIPTION
**Pull request by sjinks**
In #163 we had to build a lot of extensions from the source so that our development environment matches our production environment. However, because we had to cross-build everything for ARM64, this was painfully slow.

This PR introduces an alternative `php-fpm` image based on `alpine:3.15`. Instead of building PHP extensions from the source code, we install the prebuilt ones from the Alpine repository. This is much faster :-)

### CODE REVIEW

**Comment by pschoffer** [comment]
What is the plan with this one? We will build this new image `php-fpm-alt`, correct? Do you plan to in next steps switch VIP cli to use this image instead? And after that switch them somehow so that we still support older version of `vip` cli but don't need to build the other image?

**Comment by jesse-greathouse** [comment]
> Do you plan to in next steps switch VIP cli to use this image instead?

I think he just wants to have both FPM images available so we can test the workflow-produced alt-image image without disrupting end users with a funky FPM.

**Review by jesse-greathouse — APPROVED** [review]
Let me know if you need my help testing.

**Comment by sjinks** [comment]
@pschoffer yes, the plan is to replace the old image — after thorough testing

@jesse-greathouse yes, please

**Pull request merged**
