### PR TITLE
Makes dev-env closer to vip go

### PR DESCRIPTION
**Pull request by pschoffer**
This change sets some constants and config to behave more closely to VIP go platform.

* Also some HTTPS manipulation needed to support eg. `define( 'FORCE_SSL_ADMIN', true );`

Solves https://github.com/Automattic/vip-container-images/issues/267

### CODE REVIEW

**Review by sjinks — APPROVED** [review]

**Comment by WPprodigy** [comment]
`WPCOM_IS_VIP_ENV` being true could be misleading 😬

**Comment by pschoffer** [comment]
> `WPCOM_IS_VIP_ENV` being true could be misleading grimacing

In what way @WPprodigy ? It does seem to control a lot of places and significantly changes WP behaviour (e.g. no plugin installs)

It feels to me that in order to get closer to real platform setup we want this to be true, or?

**Comment by WPprodigy** [comment]
This constant is being used in codebases to determine if a site is on a live VIP env or if its elsewhere - like a local environment. I don't think it's very clear or true to say a local environment === a vip environment.

**Comment by pschoffer** [comment]
Gread points. I removed the setting of `WPCOM_IS_VIP_ENV` from this PR.

**Review by sjinks — APPROVED** [review]

**Pull request merged**
