### PR TITLE
Add/update delete wordpress subtree scripts

### PR DESCRIPTION
**Pull request by jesse-greathouse**
Adds scripts to safely update and remove the WP subtrees under wordpress/public

I started preparing updates of all of the WordPress images, and realized it would be helpful to have these scripts for managing the subtrees and applying patches.

Note:
wordpress/delete-version.sh does safely remove a subtree but it does not remove the entry from the .github/workflows/wordpress.yml It would be really cool to include this but Im not sure how that would work.

### CODE REVIEW

**Comment by rinatkhaziev** [comment]
This is great but let's also add the new stuff to readme 
https://github.com/Automattic/vip-container-images/tree/master/wordpress#readme

**Review by sjinks — APPROVED** [review]
LGTM, but if you don't mind, I will try to add removal of the workflow tomorrow.

**Review by rinatkhaziev — CHANGES_REQUESTED** [review]
On top of the readme, do we need to remove the GH action when we remove the corresponding version?

**Comment by jesse-greathouse** [comment]
I need to close this PR because Ive discovered that the way I'm deleting subtrees isn't doing what I expected with the git history, and leaving a really ugly and corrupted history, you can see in this PR. I will refactor it and open another PR.

**Pull request closed without merging**
